spring.datasource.url=jdbc:mysql://localhost:3306/smart_traffic?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=vansika@2007
spring.sql.init.mode=always
